language : node_js
branches:
  only:
  - master
dist: trusty
node_js:
  - "4.0"
before_script:
  - npm install
  - ng build
script :
  - echo "deploying"
install :
  - npm install -g firebase-tools
after_succes :
  - firebase deploy --token $FIREBASE_TOKEN
