#.travis.yml

language: node_js
node_js:
  - "6.9.2"

branches:
  only:
  - master
dist: trusty
node_js:
  - "6.9.2"
before_script:
  - npm install -g firebase-tools
  - npm install -g angular-cli

script:
  - ng build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
